apiVersion: apps/v1
kind: Deployment
metadata:
  name: tokenservice-webconsole
spec:
  selector:
    matchLabels:
      app: tokenservice-webconsole
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: tokenservice-webconsole
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: workingnode
                operator: In
                values: ["true"]
      containers:
      - name: tokenservice-webconsole
        image: airflowjobs/tokenservice-webconsole:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
        - name: LOG_LEVEL
          value: "DEBUG"

---

apiVersion: v1
kind: Service
metadata:
  name: tokenservice-webconsole
  labels:
    run: tokenservice-webconsole
spec:
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
  # externalIPs:
  #   - 192.168.0.119

  selector:
    app: tokenservice-webconsole

